//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarafonSKills.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeId { get; set; }
        public string EmployeeFIrstName { get; set; }
        public string EmployeeSecondName { get; set; }
        public System.DateTime EmployeeBirthDate { get; set; }
        public string EmployeeGenderName { get; set; }
        public Nullable<int> EmployeePositionId { get; set; }
        public Nullable<int> EmployeePayPeriodId { get; set; }
        public Nullable<int> EmployeePayRate { get; set; }
        public string EmployeeEmail { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual PayPeriod PayPeriod { get; set; }
        public virtual PayRate PayRate { get; set; }
        public virtual Position Position { get; set; }
    }
}
